# -*- coding: utf-8 -*-
"""DAV_EXP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16NH7PNLHA9dsbHxj8rqCWWlbUNNFy8MZ
"""

import numpy as np

"""# one dimension array"""

a=np.array([1,2,3,4,5])
a

b=np.array([6,7,8,9,10])
b

"""# two dimension array"""

c=np.array([[1,2,3,4],[6,7,8,9]])
c

d=np.array([[10,11,12,13],[14,15,16,17]])
d

"""# three dimensionality array"""

e=np.array([[20,21,22,23],[24,25,26,27],[28,29,30,31]])
e

f=np.array([[32,33,34,35],[36,37,38,39],[40,41,42,43]])
f

"""#checking array dimensions

**for one dimension**
"""

a.ndim

"""**for two dimension**"""

c.ndim

"""**for three dimension**"""

e.ndim

"""#linspace function"""

g= np.linspace(0,10,5)
g

"""#len function"""

len(b)

"""#shape function"""

d.shape

"""#diag function"""

h=np.diag(a)
h

"""#ones function"""

j=np.ones(3)
j

"""#zeroes function"""

k=np.zeros((3,3,2))
k

"""#eye function"""

l=np.eye(3,3,3)
l

"""#random function"""

m=np.random.rand(5)
m

"""#randint function"""

n=np.random.randint(1,10,3)
n

"""#reshape function"""

o=np.arange(0,6).reshape(2,3)
print(o)

"""#mask function"""

p=np.random.randint(-101,20,10)
p

mask=(p%2==0)
p[mask]

"""#tile function"""

c=np.tile(np.arange(0,40,10),(3,2))
print(c)

"""#ravel function"""

print(b.ravel())

"""#reshaping  function"""

r=np.arange(10)
r.resize((5,))
r

"""#sort function"""

v=np.sort(d,axis=1)
v

"""# write a numpy program to convert a list of numeric value into a one-dimensional numpy array
[12.23,13.32,100,36.32]
"""

s = [12.23,13.32,100,36.32]
t = np.array(s)

print(t)

"""#write a numpy program to create a 3x3 maritix with values ranging from 2 to 10"""

value = np.arange(2,11)
nm = value.reshape(3,3)
print(nm)

"""# write a numpy progrm to display all the dates from 2023 march to 2023 april"""

a=np.arange('2023-03','2023-04',dtype='datetime64[D]')
print(a)

"""# write a numpy progrm to generate six random integers between 10 to 30"""

n = np.random.randint(10,30,6)
print(n)

"""#write a numpy program to create 5x5 array random values and find the minimum and maximum and then sort it"""

e=np.array([[20,21,22,23,45],[24,25,26,27,54],[28,29,30,31,65],[324,245,355,331,685],[328,245,355,331,456]])
re = e.reshape(5,5)
print(re)

z= np.sort(e)
z

e.min()

e.max()